# Generated by Django 5.1.1 on 2024-09-27 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=64)),
                ('year', models.CharField(max_length=64)),
                ('seat', models.PositiveIntegerField(default=0)),
                ('current_seat', models.PositiveIntegerField(default=0)),
                ('q_status', models.CharField(choices=[('Available', 'Available'), ('Full', 'Full')], default='Available', max_length=64)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applys', models.ManyToManyField(blank=True, related_name='student_apply', to='quotaapp.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotaapp.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course', 'semester', 'year')},
        ),
    ]
